import type { Metadata } from "next";
import { Sawarabi_Mincho } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fortune",
  description: "Generated by Fortune",
};

const sawarabiMincho = Sawarabi_Mincho({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sawarabi-mincho", // CSS 변수 이름 설정
});

console.log("Font className:", sawarabiMincho.className); // 디버깅용
console.log("Font variable:", sawarabiMincho.variable); // 디버깅용

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={sawarabiMincho.variable}>{children}</body>
    </html>
  );
}
