import type { Metadata } from "next";
import { Noto_Serif_KR, Sawarabi_Mincho } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fortune",
  description: "Generated by Fortune",
};

// 한국어 명조체 (기본 폰트)
const notoSerifKR = Noto_Serif_KR({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-serif-kr",
});

// 일본어/한자용 폰트
const sawarabiMincho = Sawarabi_Mincho({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sawarabi-mincho",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${notoSerifKR.variable} ${sawarabiMincho.variable}`}>
        {children}
      </body>
    </html>
  );
}
